language: java
sudo: false
jdk: oraclejdk8

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
   - $HOME/.gradle/caches/
   - $HOME/.gradle/wrapper/
   - netbeans
   - jdks/local/8u111-b14/compiled

addons:
  ssh_known_hosts: updates.jmonkeyengine.org
  apt:
    packages:
    - p7zip-full
    - cabextract

# branches:
#   only:
#   - master

env:
  - BUILD_X64=true
  - BUILD_X86=true

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: cOYkCWyBNtM4QiqNbGvhCE2lFxHSnmLfRl1wLJzeDBYEDbg1nOXayRwyH1dQzWCvhDhqv2qWHHASgddE14JwnVB7p56DcaQWAJ5yn/OyY9GzaHuz59Xm6LbFbz5JfabHY7LczuBlRtISlyfz4eHD5BOvfCzx7D3GI44kQX99BCFr1mqDjQEUyTPwhLolFPL5+zx7J669ud2Ba0TywtaWsXeOUvORAXAdlQv1RRAmQvUK9DIYyq0Z3fzr/uXEBaPAz50JFXkMs00Z8Dutdiu9jd/SsRnEv0O+ns75outu6WK2UwS1xHhcdW7bkMuTmRpGoec7XbbjSaz6oYsHSp8kyuPhLEzS2ba2QIxDmOkF/erejeAMdDlsIKwRMpizRCh/8gMZR2nNEzdHQ0gbgEk83PFYgQw+amtlOk61l6THopwLtVpDiiE1Elz5ev7KqSr//qWQgoHBFabQOgE5KjfxmLDmuUNWaZyuJi6JTwsxB04NGAa3zpQ6RKQ7dgGBZF7QIQ+f648oxVlLIK+T3VAdK47s94XKTRJ0CqRoA6nI2MCaLbU9zvS8uAWoLOIKw6ec2qexPaVCE+TO0780+x6tBFSYexwH8fwmEl1nPqBldipYCLIRZV7XbJh3bhfPksXuz2B6poJ/wL5gLtWNAXnBoWyI7Vu/PHbFsn+VhLUkYSU=

install:
  - chmod u+x build_engine.sh
  - ./build_engine.sh
  # Remove Engine Source and built class files since travis is low on disk space
  - rm -rf engine/
  - ./gradlew buildSdk
  - cd jdks
  - ./download-jdks.sh
  - cd ../
  #- '[ -z "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && ant -Dstorepass="$NBM_SIGN_PASS" hudson-nightly | awk "{printf(\".\"); fflush(stdout)}" || :'
  #- '[ -z "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && scp -rp -i nbproject/private/www-updater.key build/updates/* www-updater@updates.jmonkeyengine.org:/var/www/updates/nightly/3.1/plugins || :'
  
#script:
#  - ./gradlew check
#  - ./gradlew createZipDistribution

before_deploy:
  # In case of STABLE (see hudson-stable target)
  # the above gradlew already sets the correct ant properties to build
  # Include suite.nbms again, when we upload nbms again.
  - ant -Dstorepass="$NBM_SIGN_PASS" -Dpack200.enabled=true set-spec-version build-installers unset-spec-version | awk '{printf("."); fflush(stdout)}'
  
  # Has to be done before deploy (due to the rm command)
  #- scp -rp -i nbproject/private/www-updater.key build/updates/* www-updater@updates.jmonkeyengine.org:/var/www/updates/stable/3.1/plugins
  - ./gradlew fixPlatformIndependent
  - rm -rf build/

deploy:
  provider: releases
  api_key:
    secure: IoGNk8dOmBIB/lXqgd7we7UjyFULww6y43F/Dwx2KZZ6NqC4tvDfBpqEyYhhLC0Ltgpm6vO/+0EepnqmBO5CkDYBECcwpIQX+ndgIOZQLMonXQ3glcjM5yoNtoUbFEn7xvI2ntAKbUkKmWnjNVquHF7t7jT8QfUPymUdV+f1eHapQFtcx2VuDoGF4/1fZuygS5pNPgkw7bduQo8foxlDdzSicNJ8smV0QBUZE/dVlbK1ycitZZrGkkRW/uKvsN/FX+lkl6ANb4y8AE2kcn0EarY6FH5NrQgGp5QNbGdQw1/4voFsR8Bji2UHUYuhjCuV14cgenfSQXrW4rVV/YMGaxxR/BbFB5XfZPCBfIsqfVAGH+Rkvy8/ZTBot+v9L1Pp99RZSCCtJoGPYBQagjzEOOAJplnqNHJ1D8bQo+1XElcuki/qxlO3XvXGQwTs2HMyqrnmlfdRjD5JClxx06Wke4y+KjLWtiQfjihCaQK68ixkCF4U8B2lg8nsuFNmUxUMfPCkKir4XfjuZ27y9ZNBnZQNTKOjW1cjU2GhvGyDWfK5xgfSMP/uKpAopSkWYOMaQVeUlFvMI2NtKdkb7lko6bRizEj/EWlUjhTP7TzvVGE76PJh+XeUkcNQmoFBRYOY2L+TYVs9LlKl+DQbcAHOeMYlxfq/zN7OIAh7T5AsgZk=
    # Use travis setup releases --force (gem install travis) and then anyone with push access can create the token
  # file_glob: true
  file:
   - dist/jmonkeyplatform-linux-x64.sh
   - dist/jmonkeyplatform-linux-x86.sh
   - dist/jmonkeyplatform-windows-x64.exe
   - dist/jmonkeyplatform-windows-x86.exe
   - dist/jmonkeyplatform.zip
   - dist/jmonkeyplatform-macosx.tgz
  skip_cleanup: true
  on:
    repo: jMonkeyEngine/sdk
    tags: true

before_install:
  - git fetch --unshallow -q
  - "[ $TRAVIS_PULL_REQUEST == 'false' ] && openssl aes-256-cbc -K $encrypted_ab3650240afa_key -iv $encrypted_ab3650240afa_iv -in nbproject/private/www-updater.key.enc -out nbproject/private/www-updater.key -d || :"
  - "[ $TRAVIS_PULL_REQUEST == 'false' ] && chmod 600 nbproject/private/www-updater.key || :"
  #- "[ $TRAVIS_PULL_REQUEST == 'false' ] && openssl aes-256-cbc -K $encrypted_a1949b55824a_key -iv $encrypted_a1949b55824a_iv -in private/www-updater.key.enc -out private/www-updater.key -d || :"

# before_install:
  # required libs for android build tools
  # sudo apt-get update
  # sudo apt-get install -qq p7zip-full
  # sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  # newest Android NDK
  # wget http://dl.google.com/android/ndk/android-ndk-r10c-linux-x86_64.bin -O ndk.bin
  # 7z x ndk.bin -y > /dev/null
  # export ANDROID_NDK=`pwd`/android-ndk-r10c

#after_success:
#  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && ./gradlew uploadArchives || :'
#  - '[ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && ./gradlew uploadArchives bintrayUpload || :'
